name: Controle de Execução

on:
  push:
  workflow_dispatch: 

jobs: 
  apenas-main: 
    if: ${{ github.ref == 'refs/heads/main' }} # Contexto de Job
    name: Esse job só executa na branch main 
    runs-on: ubuntu-latest
    steps:
      - name: Executando na main
        run: |
          echo "Executando job na branch main"
          echo "Branch: ${{ github.ref }}"
  feature-hotifix: 
    name: Esse job só executa nas branchs feature/ e hotifix/*
    runs-on: ubuntu-latest
    needs: [apenas-main]
    if: ${{ success()  }} # Executa com base no status do workflow. success (default), failure, always, cancelled 
    steps:
      - name: Executando feature
        if: ${{ contains(github.ref,'feature/')  }} # Contexto de Step
        run: | 
          echo "Executando job na branch feature/"
      - name: Executando hotifix
        if: ${{ contains(github.ref,'hotfix/')  }} # Contexto de Step
        run: echo "Executando job na branch hotifix/"
      - name: Envio de falhas
        if: ${{ failure() }}
        run: echo "Envio de erros|" # Nível de Step
      - name: Roda sempre
        if: ${{ success() || failure() }}
        run: echo "Roda sempre sem usar always()" # Nível de Step

      