name: Matrizes

on:
  workflow_dispatch: 

concurrency:  # Todas as pipelines com essa chave não executarão em paralelo. Dessa forma, não há concorrência.
  group: chave-concorrencia
  cancel-in-progress: true # Essa feature cancela a execução do job que está rodando para iniciar o novo
jobs: 
  matrizes: 
    strategy:
      matrix:
        versao: [16,18,20]
        plataforma: ["windows", "ubuntu"]
    runs-on: "${{ matrix.plataforma }}-latest"
    steps:
      - name: Instalação Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.versao }}
      
      - name: Exibicao dados
        run: |
          node --version
          echo ${{ runner.os }}